module.exports = {
    list   : [
        'PLAYER',
        'ULTRA',
        'HERO',
        'LEGEND',
        'TITAN',
        'YT',
        'TWITCH',
        'YOUTUBE',
        'BUILDER',
        'MAPLEAD',
        'MEDIA',
        'TRAINEE',
        'MODERATOR',
        'SR.MODERATOR',
        'C.MOD',
        'SUPPORT',
        'JR.DEV',
        'ADMIN',
        'DEVELOPER',
        'LEADER',
        'OWNER'
    ],
    convert: {
        'NONE'  : 'PLAYER',
        'ALL'   : 'PLAYER',
        'MAPDEV': 'BUILDER',
        'HELPER': 'TRAINEE',
        'MOD'   : 'MODERATOR',
        'SR.MOD': 'SR.MODERATOR',
        'SRMOD' : 'SR.MODERATOR',
        'SNRMOD': 'SR.MODERATOR',
        'CMOD'  : 'C.MOD',
        'JRDEV' : 'JR.DEV',
        'JNRDEV': 'JR.DEV',
        'DEV'   : 'DEVELOPER',
        'LT'    : 'LEADER'
    }
};